// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

/**
 * Opaque binary data
 */
@Suppress("unused")
@ExperimentalUnsignedTypes
class Binary : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Binary {
        __init(_i, _bb)
        return this
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_2_0_0()
        fun getRootAsBinary(_bb: ByteBuffer): Binary = getRootAsBinary(_bb, Binary())
        fun getRootAsBinary(_bb: ByteBuffer, obj: Binary): Binary {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startBinary(builder: FlatBufferBuilder) = builder.startTable(0)
        fun endBinary(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
