// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

@Suppress("unused")
@ExperimentalUnsignedTypes
class DateUnit private constructor() {
    companion object {
        const val DAY: Short = 0
        const val MILLISECOND: Short = 1
        val names : Array<String> = arrayOf("DAY", "MILLISECOND")
        fun name(e: Int) : String = names[e]
    }
}
