// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

/**
 * Date is either a 32-bit or 64-bit signed integer type representing an
 * elapsed time since UNIX epoch (1970-01-01), stored in either of two units:
 *
 * * Milliseconds (64 bits) indicating UNIX time elapsed since the epoch (no
 *   leap seconds), where the values are evenly divisible by 86400000
 * * Days (32 bits) since the UNIX epoch
 */
@Suppress("unused")
@ExperimentalUnsignedTypes
class Date : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Date {
        __init(_i, _bb)
        return this
    }
    val unit : Short
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getShort(o + bb_pos) else 1
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_2_0_0()
        fun getRootAsDate(_bb: ByteBuffer): Date = getRootAsDate(_bb, Date())
        fun getRootAsDate(_bb: ByteBuffer, obj: Date): Date {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDate(builder: FlatBufferBuilder, unit: Short) : Int {
            builder.startTable(1)
            addUnit(builder, unit)
            return endDate(builder)
        }
        fun startDate(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addUnit(builder: FlatBufferBuilder, unit: Short) = builder.addShort(0, unit, 1)
        fun endDate(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
