// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

/**
 * ----------------------------------------------------------------------
 * Dictionary encoding metadata
 * Maintained for forwards compatibility, in the future
 * Dictionaries might be explicit maps between integers and values
 * allowing for non-contiguous index values
 */
@Suppress("unused")
@ExperimentalUnsignedTypes
class DictionaryKind private constructor() {
    companion object {
        const val DenseArray: Short = 0
        val names : Array<String> = arrayOf("DenseArray")
        fun name(e: Int) : String = names[e]
    }
}
