// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
@ExperimentalUnsignedTypes
class Duration : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Duration {
        __init(_i, _bb)
        return this
    }
    val unit : Short
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getShort(o + bb_pos) else 1
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_2_0_0()
        fun getRootAsDuration(_bb: ByteBuffer): Duration = getRootAsDuration(_bb, Duration())
        fun getRootAsDuration(_bb: ByteBuffer, obj: Duration): Duration {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDuration(builder: FlatBufferBuilder, unit: Short) : Int {
            builder.startTable(1)
            addUnit(builder, unit)
            return endDuration(builder)
        }
        fun startDuration(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addUnit(builder: FlatBufferBuilder, unit: Short) = builder.addShort(0, unit, 1)
        fun endDuration(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
