// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
@ExperimentalUnsignedTypes
class FixedSizeBinary : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : FixedSizeBinary {
        __init(_i, _bb)
        return this
    }
    /**
     * Number of bytes per value
     */
    val byteWidth : Int
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_2_0_0()
        fun getRootAsFixedSizeBinary(_bb: ByteBuffer): FixedSizeBinary = getRootAsFixedSizeBinary(_bb, FixedSizeBinary())
        fun getRootAsFixedSizeBinary(_bb: ByteBuffer, obj: FixedSizeBinary): FixedSizeBinary {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createFixedSizeBinary(builder: FlatBufferBuilder, byteWidth: Int) : Int {
            builder.startTable(1)
            addByteWidth(builder, byteWidth)
            return endFixedSizeBinary(builder)
        }
        fun startFixedSizeBinary(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addByteWidth(builder: FlatBufferBuilder, byteWidth: Int) = builder.addInt(0, byteWidth, 0)
        fun endFixedSizeBinary(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
