// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
@ExperimentalUnsignedTypes
class Interval : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Interval {
        __init(_i, _bb)
        return this
    }
    val unit : Short
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getShort(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_2_0_0()
        fun getRootAsInterval(_bb: ByteBuffer): Interval = getRootAsInterval(_bb, Interval())
        fun getRootAsInterval(_bb: ByteBuffer, obj: Interval): Interval {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createInterval(builder: FlatBufferBuilder, unit: Short) : Int {
            builder.startTable(1)
            addUnit(builder, unit)
            return endInterval(builder)
        }
        fun startInterval(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addUnit(builder: FlatBufferBuilder, unit: Short) = builder.addShort(0, unit, 0)
        fun endInterval(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
