// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

@Suppress("unused")
@ExperimentalUnsignedTypes
class IntervalUnit private constructor() {
    companion object {
        const val YEARMONTH: Short = 0
        const val DAYTIME: Short = 1
        const val MONTHDAYNANO: Short = 2
        val names : Array<String> = arrayOf("YEAR_MONTH", "DAY_TIME", "MONTH_DAY_NANO")
        fun name(e: Int) : String = names[e]
    }
}
