// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

/**
 * Same as Utf8, but with 64-bit offsets, allowing to represent
 * extremely large data values.
 */
@Suppress("unused")
@ExperimentalUnsignedTypes
class LargeUtf8 : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : LargeUtf8 {
        __init(_i, _bb)
        return this
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_2_0_0()
        fun getRootAsLargeUtf8(_bb: ByteBuffer): LargeUtf8 = getRootAsLargeUtf8(_bb, LargeUtf8())
        fun getRootAsLargeUtf8(_bb: ByteBuffer, obj: LargeUtf8): LargeUtf8 {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startLargeUtf8(builder: FlatBufferBuilder) = builder.startTable(0)
        fun endLargeUtf8(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
