// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

/**
 * Same as Binary, but with 64-bit offsets, allowing to represent
 * extremely large data values.
 */
@Suppress("unused")
@ExperimentalUnsignedTypes
class LargeBinary : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : LargeBinary {
        __init(_i, _bb)
        return this
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_2_0_0()
        fun getRootAsLargeBinary(_bb: ByteBuffer): LargeBinary = getRootAsLargeBinary(_bb, LargeBinary())
        fun getRootAsLargeBinary(_bb: ByteBuffer, obj: LargeBinary): LargeBinary {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startLargeBinary(builder: FlatBufferBuilder) = builder.startTable(0)
        fun endLargeBinary(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
