// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

/**
 * These are stored in the flatbuffer in the Type union below
 */
@Suppress("unused")
@ExperimentalUnsignedTypes
class Null : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Null {
        __init(_i, _bb)
        return this
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_2_0_0()
        fun getRootAsNull(_bb: ByteBuffer): Null = getRootAsNull(_bb, Null())
        fun getRootAsNull(_bb: ByteBuffer, obj: Null): Null {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startNull(builder: FlatBufferBuilder) = builder.startTable(0)
        fun endNull(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
