// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

@Suppress("unused")
@ExperimentalUnsignedTypes
class Precision private constructor() {
    companion object {
        const val HALF: Short = 0
        const val SINGLE: Short = 1
        const val DOUBLE: Short = 2
        val names : Array<String> = arrayOf("HALF", "SINGLE", "DOUBLE")
        fun name(e: Int) : String = names[e]
    }
}
