// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

/**
 * A Struct_ in the flatbuffer metadata is the same as an Arrow Struct
 * (according to the physical memory layout). We used Struct_ here as
 * Struct is a reserved word in Flatbuffers
 */
@Suppress("unused")
@ExperimentalUnsignedTypes
class Struct_ : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Struct_ {
        __init(_i, _bb)
        return this
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_2_0_0()
        fun getRootAsStruct_(_bb: ByteBuffer): Struct_ = getRootAsStruct_(_bb, Struct_())
        fun getRootAsStruct_(_bb: ByteBuffer, obj: Struct_): Struct_ {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startStruct_(builder: FlatBufferBuilder) = builder.startTable(0)
        fun endStruct_(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
