// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

@Suppress("unused")
@ExperimentalUnsignedTypes
class TimeUnit private constructor() {
    companion object {
        const val SECOND: Short = 0
        const val MILLISECOND: Short = 1
        const val MICROSECOND: Short = 2
        const val NANOSECOND: Short = 3
        val names : Array<String> = arrayOf("SECOND", "MILLISECOND", "MICROSECOND", "NANOSECOND")
        fun name(e: Int) : String = names[e]
    }
}
