// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

/**
 * Unicode with UTF-8 encoding
 */
@Suppress("unused")
@ExperimentalUnsignedTypes
class Utf8 : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Utf8 {
        __init(_i, _bb)
        return this
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_2_0_0()
        fun getRootAsUtf8(_bb: ByteBuffer): Utf8 = getRootAsUtf8(_bb, Utf8())
        fun getRootAsUtf8(_bb: ByteBuffer, obj: Utf8): Utf8 {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startUtf8(builder: FlatBufferBuilder) = builder.startTable(0)
        fun endUtf8(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
