<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace org\apache\arrow\flatbuf;

class DateUnit
{
    const DAY = 0;
    const MILLISECOND = 1;

    private static $names = array(
        DateUnit::DAY=>"DAY",
        DateUnit::MILLISECOND=>"MILLISECOND",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
