<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace org\apache\arrow\flatbuf;

/// ----------------------------------------------------------------------
/// Endianness of the platform producing the data
class Endianness
{
    const Little = 0;
    const Big = 1;

    private static $names = array(
        Endianness::Little=>"Little",
        Endianness::Big=>"Big",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
