<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace org\apache\arrow\flatbuf;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class FixedSizeList extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return FixedSizeList
     */
    public static function getRootAsFixedSizeList(ByteBuffer $bb)
    {
        $obj = new FixedSizeList();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return FixedSizeList
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /// Number of list items per value
    /**
     * @return int
     */
    public function getListSize()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startFixedSizeList(FlatBufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return FixedSizeList
     */
    public static function createFixedSizeList(FlatBufferBuilder $builder, $listSize)
    {
        $builder->startObject(1);
        self::addListSize($builder, $listSize);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addListSize(FlatBufferBuilder $builder, $listSize)
    {
        $builder->addIntX(0, $listSize, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endFixedSizeList(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
