<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace org\apache\arrow\flatbuf;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class FloatingPoint extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return FloatingPoint
     */
    public static function getRootAsFloatingPoint(ByteBuffer $bb)
    {
        $obj = new FloatingPoint();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return FloatingPoint
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return short
     */
    public function getPrecision()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getShort($o + $this->bb_pos) : \org\apache\arrow\flatbuf\Precision::HALF;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startFloatingPoint(FlatBufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return FloatingPoint
     */
    public static function createFloatingPoint(FlatBufferBuilder $builder, $precision)
    {
        $builder->startObject(1);
        self::addPrecision($builder, $precision);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param short
     * @return void
     */
    public static function addPrecision(FlatBufferBuilder $builder, $precision)
    {
        $builder->addShortX(0, $precision, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endFloatingPoint(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
