<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace org\apache\arrow\flatbuf;

class IntervalUnit
{
    const YEAR_MONTH = 0;
    const DAY_TIME = 1;
    const MONTH_DAY_NANO = 2;

    private static $names = array(
        IntervalUnit::YEAR_MONTH=>"YEAR_MONTH",
        IntervalUnit::DAY_TIME=>"DAY_TIME",
        IntervalUnit::MONTH_DAY_NANO=>"MONTH_DAY_NANO",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
