<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace org\apache\arrow\flatbuf;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

/// Same as Utf8, but with 64-bit offsets, allowing to represent
/// extremely large data values.
class LargeUtf8 extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return LargeUtf8
     */
    public static function getRootAsLargeUtf8(ByteBuffer $bb)
    {
        $obj = new LargeUtf8();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return LargeUtf8
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startLargeUtf8(FlatBufferBuilder $builder)
    {
        $builder->StartObject(0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return LargeUtf8
     */
    public static function createLargeUtf8(FlatBufferBuilder $builder, )
    {
        $builder->startObject(0);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endLargeUtf8(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
