<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace org\apache\arrow\flatbuf;

class MetadataVersion
{
    /// 0.1.0 (October 2016).
    const V1 = 0;
    /// 0.2.0 (February 2017). Non-backwards compatible with V1.
    const V2 = 1;
    /// 0.3.0 -> 0.7.1 (May - December 2017). Non-backwards compatible with V2.
    const V3 = 2;
    /// >= 0.8.0 (December 2017). Non-backwards compatible with V3.
    const V4 = 3;
    /// >= 1.0.0 (July 2020. Backwards compatible with V4 (V5 readers can read V4
    /// metadata and IPC messages). Implementations are recommended to provide a
    /// V4 compatibility mode with V5 format changes disabled.
    ///
    /// Incompatible changes between V4 and V5:
    /// - Union buffer layout has changed. In V5, Unions don't have a validity
    ///   bitmap buffer.
    const V5 = 4;

    private static $names = array(
        MetadataVersion::V1=>"V1",
        MetadataVersion::V2=>"V2",
        MetadataVersion::V3=>"V3",
        MetadataVersion::V4=>"V4",
        MetadataVersion::V5=>"V5",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
