<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace org\apache\arrow\flatbuf;

class Precision
{
    const HALF = 0;
    const SINGLE = 1;
    const DOUBLE = 2;

    private static $names = array(
        Precision::HALF=>"HALF",
        Precision::SINGLE=>"SINGLE",
        Precision::DOUBLE=>"DOUBLE",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
