<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace org\apache\arrow\flatbuf;

class UnionMode
{
    const Sparse = 0;
    const Dense = 1;

    private static $names = array(
        UnionMode::Sparse=>"Sparse",
        UnionMode::Dense=>"Dense",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
