--[[ org.apache.arrow.flatbuf.Binary

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 2.0.5

  Declared by  : //Schema.fbs
  Rooting type : org.apache.arrow.flatbuf.Schema (//Schema.fbs)

--]]

local flatbuffers = require('flatbuffers')

-- Opaque binary data
local Binary = {}
local mt = {}

function Binary.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function Binary.Start(builder)
  builder:StartObject(0)
end

function Binary.End(builder)
  return builder:EndObject()
end

return Binary