--[[ org.apache.arrow.flatbuf.DictionaryKind

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 2.0.5

  Declared by  : //Schema.fbs
  Rooting type : org.apache.arrow.flatbuf.Schema (//Schema.fbs)

--]]

-- ----------------------------------------------------------------------
-- Dictionary encoding metadata
-- Maintained for forwards compatibility, in the future
-- Dictionaries might be explicit maps between integers and values
-- allowing for non-contiguous index values
local DictionaryKind = {
  DenseArray = 0,
}

return DictionaryKind