--[[ org.apache.arrow.flatbuf.Endianness

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 2.0.5

  Declared by  : //Schema.fbs
  Rooting type : org.apache.arrow.flatbuf.Schema (//Schema.fbs)

--]]

-- ----------------------------------------------------------------------
-- Endianness of the platform producing the data
local Endianness = {
  Little = 0,
  Big = 1,
}

return Endianness