--[[ org.apache.arrow.flatbuf.FixedSizeList

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 2.0.5

  Declared by  : //Schema.fbs
  Rooting type : org.apache.arrow.flatbuf.Schema (//Schema.fbs)

--]]

local flatbuffers = require('flatbuffers')

local FixedSizeList = {}
local mt = {}

function FixedSizeList.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

-- Number of list items per value
function mt:ListSize()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Int32, self.view.pos + o)
  end
  return 0
end

function FixedSizeList.Start(builder)
  builder:StartObject(1)
end

function FixedSizeList.AddListSize(builder, listSize)
  builder:PrependInt32Slot(0, listSize, 0)
end

function FixedSizeList.End(builder)
  return builder:EndObject()
end

return FixedSizeList