--[[ org.apache.arrow.flatbuf.FixedSizeBinary

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 2.0.5

  Declared by  : //Schema.fbs
  Rooting type : org.apache.arrow.flatbuf.Schema (//Schema.fbs)

--]]

local flatbuffers = require('flatbuffers')

local FixedSizeBinary = {}
local mt = {}

function FixedSizeBinary.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

-- Number of bytes per value
function mt:ByteWidth()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Int32, self.view.pos + o)
  end
  return 0
end

function FixedSizeBinary.Start(builder)
  builder:StartObject(1)
end

function FixedSizeBinary.AddByteWidth(builder, byteWidth)
  builder:PrependInt32Slot(0, byteWidth, 0)
end

function FixedSizeBinary.End(builder)
  return builder:EndObject()
end

return FixedSizeBinary