--[[ org.apache.arrow.flatbuf.Int

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 2.0.5

  Declared by  : //Schema.fbs
  Rooting type : org.apache.arrow.flatbuf.Schema (//Schema.fbs)

--]]

local flatbuffers = require('flatbuffers')

local Int = {}
local mt = {}

function Int.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:BitWidth()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Int32, self.view.pos + o)
  end
  return 0
end

function mt:IsSigned()
  local o = self.view:Offset(6)
  if o ~= 0 then
    return (self.view:Get(flatbuffers.N.Bool, self.view.pos + o) ~=0)
  end
  return false
end

function Int.Start(builder)
  builder:StartObject(2)
end

function Int.AddBitWidth(builder, bitWidth)
  builder:PrependInt32Slot(0, bitWidth, 0)
end

function Int.AddIsSigned(builder, isSigned)
  builder:PrependBoolSlot(1, isSigned, false)
end

function Int.End(builder)
  return builder:EndObject()
end

return Int