--[[ org.apache.arrow.flatbuf.LargeBinary

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 2.0.5

  Declared by  : //Schema.fbs
  Rooting type : org.apache.arrow.flatbuf.Schema (//Schema.fbs)

--]]

local flatbuffers = require('flatbuffers')

-- Same as Binary, but with 64-bit offsets, allowing to represent
-- extremely large data values.
local LargeBinary = {}
local mt = {}

function LargeBinary.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function LargeBinary.Start(builder)
  builder:StartObject(0)
end

function LargeBinary.End(builder)
  return builder:EndObject()
end

return LargeBinary