--[[ org.apache.arrow.flatbuf.Null

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 2.0.5

  Declared by  : //Schema.fbs
  Rooting type : org.apache.arrow.flatbuf.Schema (//Schema.fbs)

--]]

local flatbuffers = require('flatbuffers')

-- These are stored in the flatbuffer in the Type union below
local Null = {}
local mt = {}

function Null.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function Null.Start(builder)
  builder:StartObject(0)
end

function Null.End(builder)
  return builder:EndObject()
end

return Null