--[[ org.apache.arrow.flatbuf.Struct_

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 2.0.5

  Declared by  : //Schema.fbs
  Rooting type : org.apache.arrow.flatbuf.Schema (//Schema.fbs)

--]]

local flatbuffers = require('flatbuffers')

-- A Struct_ in the flatbuffer metadata is the same as an Arrow Struct
-- (according to the physical memory layout). We used Struct_ here as
-- Struct is a reserved word in Flatbuffers
local Struct_ = {}
local mt = {}

function Struct_.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function Struct_.Start(builder)
  builder:StartObject(0)
end

function Struct_.End(builder)
  return builder:EndObject()
end

return Struct_