--[[ org.apache.arrow.flatbuf.UnionMode

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 2.0.5

  Declared by  : //Schema.fbs
  Rooting type : org.apache.arrow.flatbuf.Schema (//Schema.fbs)

--]]

local UnionMode = {
  Sparse = 0,
  Dense = 1,
}

return UnionMode