--[[ org.apache.arrow.flatbuf.Utf8

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 2.0.5

  Declared by  : //Schema.fbs
  Rooting type : org.apache.arrow.flatbuf.Schema (//Schema.fbs)

--]]

local flatbuffers = require('flatbuffers')

-- Unicode with UTF-8 encoding
local Utf8 = {}
local mt = {}

function Utf8.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function Utf8.Start(builder)
  builder:StartObject(0)
end

function Utf8.End(builder)
  return builder:EndObject()
end

return Utf8